name: Build Temp Spoofer on Windows

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Compile spoofer manually
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"
          cl.exe /EHsc main.cpp portable_executable.cpp /Fe:TempSpoofer.exe /link /LIBPATH:lib proxine.lib

      - name: Upload built executable
        uses: actions/upload-artifact@v4
        with:
          name: TempSpoofer-Release
          path: TempSpoofer.exe
